service: my-nestjs-app

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: 5432
      DB_USERNAME: ${env:DB_USERNAME}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_NAME: ${env:DB_NAME}

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  dotenv:
    include:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
